name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Install OS dependencies
        run: sudo apt-get install libhdf5-dev -y
      
      - name: Install build dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      
      - name: Install project dependencies
        run: python -m pip install -r requirements.txt
      
      # - name: Update Conda and channels
      #   run: |
      #     conda update conda --yes
      #     conda update --all --yes

      # - name: Install project dependencies
      #   run: conda env create --file environment.yml && conda activate my_env

      - name: Build distribution package
        run: python setup.py sdist bdist_wheel

      # - name: Upload to TestPyPI
      #   run: python3 -m twine upload dist/* --verbose
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
      #     TWINE_REPOSITORY: testpypi
      
      - name: Upload to PyPI
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
